# PII detection policy: which detector(s) compose the CompositePIIDetector.
# "presidio" (spaCy NER, plus its own registry of custom PatternRecognizers
# — marital_or_family, nationality, and the NZ-specific IRD number/driver's
# licence/postcode-line formats) is the only detector: fully local, no LLM
# call anywhere in the PII path. See presidio_detector.py's module
# docstring for the per-kind coverage breakdown.
detectors:
  - presidio

# Tuning for "presidio":
presidio:
  score_threshold: 0.4
